# 10. Data Analytics 3

1. Implement Simple Naïve Bayes classification algorithm using Python/R on iris.csv
dataset.

3. Compute Confusion matrix to find TP, FP, TN, FN, Accuracy, Error rate,
Precision, Recall on the given dataset.

In [33]:
import numpy as np
import seaborn as sns
import pandas as pd

In [34]:
ds = pd.read_csv( "iris.csv" )
ds

sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [35]:
def normalize( feature ):
    ds[ feature ] = ( ds[ feature ] - ds[ feature ].min() ) / ( ds[feature].max() - ds[feature].min() )

for feature in features:
    normalize( feature )
ds

sepal_length  sepal_width  petal_length  petal_width    species
0        0.222222     0.625000      0.067797     0.041667     setosa
1        0.166667     0.416667      0.067797     0.041667     setosa
2        0.111111     0.500000      0.050847     0.041667     setosa
3        0.083333     0.458333      0.084746     0.041667     setosa
4        0.194444     0.666667      0.067797     0.041667     setosa
..            ...          ...           ...          ...        ...
145      0.666667     0.416667      0.711864     0.916667  virginica
146      0.555556     0.208333      0.677966     0.750000  virginica
147      0.611111     0.416667      0.711864     0.791667  virginica
148      0.527778     0.583333      0.745763     0.916667  virginica
149      0.444444     0.416667      0.694915     0.708333  virginica

[150 rows x 5 columns]

In [50]:
# label encoding
ds.loc[ ds.species == "setosa" , "species" ] = 0
ds.loc[ ds.species == "versicolor" , "species" ] = 1
ds.loc[ ds.species == "virginica" , "species" ] = 2
ds = ds.astype( { "species" : "int" } )
ds.dtypes

sepal_length    float64
sepal_width     float64
petal_length    float64
petal_width     float64
species           int32
dtype: object

In [51]:
features = ds.drop( [ "species" ] , axis=1 ).columns
label = "species"
classes = np.unique( ds[label] )
print( features )
print( label )
print( classes )

Index(['sepal_length', 'sepal_width', 'petal_length', 'petal_width'], dtype='object')
species
[0 1 2]


## Implementation of Gaussian NB from scratch

In [52]:
import math

def gaussian_pdf( mean: float , std: float ):
    def pdf( x ):
        return (1.0 / (std * math.sqrt( 2 * math.pi ))) * math.exp( -0.5 * ((x - mean)/std)**2 )
    return pdf

def compute_prior( class_: int ) -> float:
    print( train_ds[ train_ds["species"] == class_ ] )
    return len( train_ds[ train_ds["species"] == class_ ] ) / len( train_ds )

def compute_log_likelihood( sample , class_: int ) -> float:
    prior_prob = compute_prior( class_ )
    posterior_prob = 0.0
    for i , feature in enumerate(features):
        pdf = gaussian_pdf( 
            train_ds[ train_ds[label] == class_ ][feature].mean() , 
            train_ds[ train_ds[label] == class_ ][feature].std() 
        )
        posterior_prob += math.log( pdf( sample[i] ) )
    print( prior_prob )
    return posterior_prob + math.log( prior_prob )

def classifier( sample ):
    max_likelihood = -math.inf
    max_likelihood_class = None
    for class_ in classes:
        class_likelihood = compute_log_likelihood( sample , class_ )
        if class_likelihood > max_likelihood:
            max_likelihood = class_likelihood
            max_likelihood_class = class_
    return max_likelihood_class

In [53]:
def train_test_split( test_split = 0.3 ):
    global ds
    ds = ds.sample(frac=1)
    num_test_samples = int(len( ds ) * test_split)
    test_ds = ds.head( num_test_samples )
    train_ds = ds.tail( len(ds) - num_test_samples )
    return train_ds , test_ds

train_ds , test_ds = train_test_split()
print( train_ds )
target_labels = list( test_ds[label] )
pred_labels = []
for test_sample in test_ds.to_numpy():
    pred_y = classifier( test_sample[ : -1 ] )
    pred_labels.append( pred_y )

     sepal_length  sepal_width  petal_length  petal_width  species
81       0.333333     0.166667      0.457627     0.375000        1
20       0.305556     0.583333      0.118644     0.041667        0
80       0.333333     0.166667      0.474576     0.416667        1
131      1.000000     0.750000      0.915254     0.791667        2
108      0.666667     0.208333      0.813559     0.708333        2
..            ...          ...           ...          ...      ...
132      0.583333     0.333333      0.779661     0.875000        2
0        0.222222     0.625000      0.067797     0.041667        0
49       0.194444     0.541667      0.067797     0.041667        0
111      0.583333     0.291667      0.728814     0.750000        2
82       0.416667     0.291667      0.491525     0.458333        1

[105 rows x 5 columns]
    sepal_length  sepal_width  petal_length  petal_width  species
20      0.305556     0.583333      0.118644     0.041667        0
25      0.194444     0.416667      0.101

In [54]:
from sklearn.metrics import recall_score , precision_score , f1_score , accuracy_score

recall = recall_score( target_labels , pred_labels , average=None )
print( recall )

precision = precision_score( target_labels , pred_labels , average=None )
print( precision )

accuracy = accuracy_score( target_labels , pred_labels )
print( accuracy )

f1 = f1_score( target_labels , pred_labels , average=None )
print( f1 )

[1.         0.90909091 0.875     ]
[1.         0.83333333 0.93333333]
0.9333333333333333
[1.         0.86956522 0.90322581]


## Implementation with scikit-learn's `GaussianNB`

In [57]:
from sklearn.naive_bayes import GaussianNB

train_X = train_ds.values[ : , :-1 ]
test_X = test_ds.values[ : , :-1 ]
train_y = train_ds.values[ : , -1 ]
test_y = test_ds.values[ : , -1 ]

clf = GaussianNB()
clf.fit( train_X , train_y )
pred_y = clf.predict( test_X )

In [58]:
from sklearn.metrics import recall_score , precision_score , f1_score , accuracy_score

recall = recall_score( test_y , pred_y , average=None )
print( recall )

precision = precision_score( test_y , pred_y , average=None )
print( precision )

accuracy = accuracy_score( test_y , pred_y )
print( accuracy )

f1 = f1_score( test_y , pred_y , average=None )
print( f1 )

[1.         0.90909091 0.875     ]
[1.         0.83333333 0.93333333]
0.9333333333333333
[1.         0.86956522 0.90322581]
